In [1]:
import script.create_new_csv
import script.create_new_images


In [2]:
script.create_new_csv.create_new_csv()

The new database was created in: 
 ./data/new_accumulated_capital.csv


In [3]:
script.create_new_csv.create_new_csv()

The new database was created in: 
 ./data/new_accumulated_capital.csv


# Exploratory

In [4]:
import pandas as pd
import numpy as np
from os import getcwd

#to get the current working directory
directory = getcwd()
df_raw = pd.read_csv(directory+"/data/data_raw.csv")
df_raw.head()


Unnamed: 0  initial_age  weight  family_kind  race  marital_status  \
0           0           57     616            2     1               3   
1           1           45     591            1     1               1   
2           2           59     613            1     1               1   
3           3           62     656            1     1               1   
4           4           45     567            2     1               5   

   accumulated_capital  annual_contribution     income  
0       -153263.200759                 0.23   42658.02  
1        161474.307306                 0.24  248327.61  
2         14209.331170                 0.09   24371.94  
3        -77270.897162                 0.17   48788.04  
4        282353.182490                 0.22   47808.66

In [5]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47626 entries, 0 to 47625
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           47626 non-null  int64  
 1   initial_age          47626 non-null  int64  
 2   weight               47626 non-null  int64  
 3   family_kind          47626 non-null  int64  
 4   race                 47626 non-null  int64  
 5   marital_status       47626 non-null  int64  
 6   accumulated_capital  47626 non-null  float64
 7   annual_contribution  47626 non-null  float64
 8   income               47626 non-null  float64
dtypes: float64(3), int64(6)
memory usage: 3.3 MB


In [6]:
df_raw[['weight','accumulated_capital','annual_contribution','income']].describe()

weight  accumulated_capital  annual_contribution         income
count  47626.000000         4.762600e+04         47626.000000   47626.000000
mean    1551.159535         2.483036e+04             0.175277   70240.892997
std      942.788098         1.705045e+05             0.101389   49720.565014
min       98.000000        -5.119091e+05             0.000000     250.650000
25%      811.250000        -8.116163e+04             0.090000   33878.760000
50%     1500.000000         2.280218e+04             0.180000   59084.150000
75%     1971.000000         1.016781e+05             0.260000   94320.602500
max     9349.000000         1.111905e+06             0.350000  473601.750000

In [7]:
t1 = df_raw['initial_age'].unique()
t1.sort()
print(t1)

[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63]


In [8]:
t2 = df_raw['race'].unique()
t2.sort()
print(t2)

[1 2 3 4]


In [9]:
t3 = df_raw['family_kind'].unique()
t3.sort()
print(t3)

[1 2 3]


In [10]:
t3 = df_raw['marital_status'].unique()
t3.sort()
print(t3)

[1 2 3 4 5]
